version: '3.8'
services:
  db:
    image: 'mysql:8.0'
    container_name: blogosphere-db
    command: --sql_mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_DATABASE: blogosphere
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'